-- MySQL Script generated by MySQL Workbench
-- Sun Apr 17 23:46:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rebu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rebu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rebu` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `rebu` ;

-- -----------------------------------------------------
-- Table `rebu`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rebu`.`driver` (
  `salutation` VARCHAR(40) NOT NULL,
  `first_name_Driver` VARCHAR(40) NULL DEFAULT NULL,
  `last_name` VARCHAR(40) NULL DEFAULT NULL,
  `Phone_Number` CHAR(11) NULL DEFAULT NULL,
  `Email_Address` VARCHAR(40) NULL DEFAULT NULL,
  `Vehicle_Make` VARCHAR(30) NULL DEFAULT NULL,
  `Vehicle_Year` DATE NULL DEFAULT NULL,
  `Licence_Plate_Number` VARCHAR(20) NULL DEFAULT NULL,
  `Number_of_Speeding_Tickets_in_the_last_5_Years` INT NOT NULL,
  `Number_of_Accidents_in_last_5_years` INT NULL DEFAULT NULL,
  PRIMARY KEY (`salutation`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rebu`.`pickup_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rebu`.`pickup_schedule` (
  `Pickup_Location` VARCHAR(40) NOT NULL,
  `Pickup_Date` DATE NULL DEFAULT NULL,
  `Pickup_Time` DATETIME NULL DEFAULT NULL,
  `Dropoff_Location` VARCHAR(40) NULL DEFAULT NULL,
  `Cost_of_Ride` FLOAT NULL DEFAULT NULL,
  `HST_Amount` FLOAT NULL DEFAULT NULL,
  `Driver_Satisfaction_Survey` INT NULL DEFAULT NULL,
  `Debit_or_Credit` VARCHAR(40) NULL DEFAULT NULL,
  `TAX_HST` FLOAT GENERATED ALWAYS AS ((`Cost_of_Ride` * 0.13)) VIRTUAL,
  `Total_Cost` FLOAT GENERATED ALWAYS AS ((`Cost_of_Ride` + `TAX_HST`)) VIRTUAL,
  `rider_drivers_Rider_Driver_ID` INT NOT NULL,
  PRIMARY KEY (`Pickup_Location`),
  INDEX `fk_pickup_schedule_rider_drivers_idx` (`rider_drivers_Rider_Driver_ID` ASC) VISIBLE,
  CONSTRAINT `fk_pickup_schedule_rider_drivers`
    FOREIGN KEY (`rider_drivers_Rider_Driver_ID`)
    REFERENCES `rebu`.`rider_drivers` (`Rider_Driver_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rebu`.`rider_drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rebu`.`rider_drivers` (
  `Rider_Driver_ID` INT NOT NULL,
  `riders_Name_of_Rider` VARCHAR(40) NOT NULL,
  `driver_salutation` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`Rider_Driver_ID`),
  INDEX `fk_rider_drivers_riders1_idx` (`riders_Name_of_Rider` ASC) VISIBLE,
  INDEX `fk_rider_drivers_driver1_idx` (`driver_salutation` ASC) VISIBLE,
  CONSTRAINT `fk_rider_drivers_riders1`
    FOREIGN KEY (`riders_Name_of_Rider`)
    REFERENCES `rebu`.`riders` (`Name_of_Rider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rider_drivers_driver1`
    FOREIGN KEY (`driver_salutation`)
    REFERENCES `rebu`.`driver` (`salutation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rebu`.`riders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rebu`.`riders` (
  `Name_of_Rider` VARCHAR(40) NOT NULL,
  `Address` VARCHAR(30) NULL DEFAULT NULL,
  `Phone_Number` CHAR(11) NULL DEFAULT NULL,
  `Credit_or_Debit_Number` VARCHAR(40) NULL DEFAULT NULL,
  `Namme_on_Card` VARCHAR(30) NULL DEFAULT NULL,
  `Credit_Card_Expiry_Date` CHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`Name_of_Rider`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
